services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "unless-stopped"
    networks:
      - gryps-network

  # migrate:
  #   build: .
  #   image: grypsiarze-migrate:prod
  #   command: ["node", "src/db/migrate.js"]
  #   environment:
  #     MYSQL_DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: "no"
  #   networks:
  #     - gryps-network

  web:
    build: .
    image: grypsiarze-web:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: "unless-stopped"
    command: ["node", "dist/src/server.js"]
    networks:
      - proxy
      - gryps-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gryps-web.rule=Host(`gryps.home.movo.site`) || Host(`gryps.movo.site`)"
      - "traefik.http.routers.gryps-web.middlewares=https-only@file"
      - "traefik.http.routers.gryps-web.tls=true"
      - "traefik.http.routers.gryps-web.service=gryps-web"
      - "traefik.http.services.gryps-web.loadbalancer.server.port=3000"

  bot:
    build: .
    image: grypsiarze-bot:prod
    environment:
      NODE_ENV: production
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL}
      TWITCH_USERNAME: ${TWITCH_USERNAME}
      TWITCH_OAUTH_TOKEN: ${TWITCH_OAUTH_TOKEN}
      CHANNEL_NAME: ${CHANNEL_NAME}
    depends_on:
      - db
      - migrate
    restart: "unless-stopped"
    command: ["node", "dist/src/bot.js"]
    networks:
      - gryps-network

volumes:
  db-data:
networks:
  gryps-network:
  proxy:
    external: true
